### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by KotoHacker** [SourceWriters/LoginPlus#13] opened 2021-01-02 15:09 UTC
The plugin needs specific optimization. When you start a server with 4GB of RAM and when 5 players were joining on the server, the server crashes with an error of insufficient RAM. Also, the plugin itself eats the processor well.

**Comment by KotoHacker** [comment] 2021-01-02 15:13
Version: 1.16.4; Paper-356.

**Comment by YellowPhoenix18** [comment] 2021-01-03 00:47
Probably a duplicate of #11

**Closed** 2021-02-05 12:42 UTC
