### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by WojtekPlay** [SourceWriters/LoginPlus#34] opened 2022-06-28 15:29 UTC
when it will support 1.19 or at least be fixed on that version beacuse it breaks after i join the server (nothing shows up)

**Comment by Lauriichan** [comment] 2022-06-28 15:33
Can you provide a log and stuff like that?

**Comment by PSYCHEER** [comment] 2023-02-27 16:20
`PSYCHEER joined the game
[16:19:40 INFO]: PSYCHEER[/xxx.xxx.xxx.xxx:12345] logged in with entity id 75 at ([world]-216.23975034293875, 63.0, -150.27894203381143)
[16:19:40 INFO]: [STDOUT] [net.sourcewriters.minecraft.vcompat.VersionCompatProvider] Initializing vCompat on with 'v1_19_R2' core on '1.19.3'!
[16:19:40 WARN]: [LoginPlus] Task #17 for LoginPlus v3.2.1 generated an exception
java.lang.IllegalStateException: Failed to initialize vCompat implementation
        at net.sourcewriters.minecraft.vcompat.VersionCompatProvider.get(VersionCompatProvider.java:31) ~[vCompat.jar:?]
        at com.syntaxphoenix.loginplus.utils.PlayerHelper.sendTitle(PlayerHelper.java:13) ~[LoginPlus-3.2.1.jar:?]
        at com.syntaxphoenix.loginplus.utils.login.LoginCallback.handleLogin(LoginCallback.java:70) ~[LoginPlus-3.2.1.jar:?]
        at com.syntaxphoenix.loginplus.utils.login.LoginManager.callbackUser(LoginManager.java:32) ~[LoginPlus-3.2.1.jar:?]
        at com.syntaxphoenix.loginplus.accounts.manager.AccountManager.setLocalAccount(AccountManager.java:36) ~[LoginPlus-3.2.1.jar:?]
        at com.syntaxphoenix.loginplus.accounts.tasks.SyncSetLocalAccount.run(SyncSetLocalAccount.java:22) ~[LoginPlus-3.2.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1921]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1921]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1921]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.3.jar:git-Purpur-1921]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1921]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1921]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1921]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Can't initialize VersionControl
        at net.sourcewriters.minecraft.vcompat.VersionCompat.initControl(VersionCompat.java:36) ~[vCompat.jar:?]
        at net.sourcewriters.minecraft.vcompat.VersionCompat.init(VersionCompat.java:22) ~[vCompat.jar:?]
        at net.sourcewriters.minecraft.vcompat.VersionCompatProvider.get(VersionCompatProvider.java:29) ~[vCompat.jar:?]
        ... 13 more`

Paper, pufferfish, purpur, spigot 1.19.3 making this

**Comment by YellowPhoenix18** [comment] 2023-02-27 16:27
Closing in favour of #38

**Closed as completed by YellowPhoenix18** 2023-02-27 16:27 UTC
Labels: help wanted
