### ISSUE TITLE
I give the status of OP

### ISSUE THREAD

**Issue by Beartherter13** [SourceWriters/LoginPlus#12] opened 2020-12-08 12:08 UTC
I take the status OP , and after relog cant log in with my own password

**Comment by YellowPhoenix18** [comment] 2021-01-03 00:48
Could be a argon2-issue, so may be a duplicate of #11 , can you please provide a log?

**Comment by YellowPhoenix18** [comment] 2021-02-13 01:29
This problem will get fixed with v3, which will get released in the next minutes

**Closed by YellowPhoenix18** 2021-02-13 01:29 UTC
